#!/usr/bin/env bash
#
# Deploy konduktiv-ovodaert to home.pl shared hosting at novaak.net/konduktiv_ovodaert/web.
#
# Pre-reqs:
#   - DDEV project up (`ddev start`); local DB is the source of truth.
#   - SSH alias 'tarhely' configured for the home.pl account.
#   - Local composer + rsync.
#   - composer.json already has the PHP 8.2 platform pin and patches in
#     composer.patches.json/patches/php-8.2-compat/. Don't deploy without those.
#
# Required env vars:
#   NOVAAK_DB_PASS      home.pl DB password for 13319505_konduktiv_ovodaert.
#   NOVAAK_HASH_SALT    Random hex string used as Drupal $settings['hash_salt'].
#                       Generate once with: php -r 'echo bin2hex(random_bytes(40));'
#
# Optional env vars (defaults shown):
#   NOVAAK_DB_USER=13319505_konduktiv_ovodaert
#   NOVAAK_DB_NAME=13319505_konduktiv_ovodaert
#   NOVAAK_DB_HOST=mysql8
#   NOVAAK_SSH=tarhely
#   NOVAAK_TARGET=/home/serwer1365505/public_html/novaak.net/novaak.net/konduktiv_ovodaert
#   NOVAAK_BUILD_DIR=/tmp/konduktiv-deploy-build
#   NOVAAK_SKIP_DB=0  (set to 1 to skip exporting/importing the DB)

set -euo pipefail

: "${NOVAAK_DB_PASS:?NOVAAK_DB_PASS is required}"
: "${NOVAAK_HASH_SALT:?NOVAAK_HASH_SALT is required (generate with: php -r 'echo bin2hex(random_bytes(40));')}"

NOVAAK_DB_USER="${NOVAAK_DB_USER:-13319505_konduktiv_ovodaert}"
NOVAAK_DB_NAME="${NOVAAK_DB_NAME:-13319505_konduktiv_ovodaert}"
NOVAAK_DB_HOST="${NOVAAK_DB_HOST:-mysql8}"
NOVAAK_SSH="${NOVAAK_SSH:-tarhely}"
NOVAAK_TARGET="${NOVAAK_TARGET:-/home/serwer1365505/public_html/novaak.net/novaak.net/konduktiv_ovodaert}"
NOVAAK_BUILD_DIR="${NOVAAK_BUILD_DIR:-/tmp/konduktiv-deploy-build}"
NOVAAK_SKIP_DB="${NOVAAK_SKIP_DB:-0}"

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DB_DUMP="/tmp/konduktiv-db-$$.sql.gz"

echo "==> Project root: $PROJECT_ROOT"
echo "==> Build dir:    $NOVAAK_BUILD_DIR"
echo "==> Target:       $NOVAAK_SSH:$NOVAAK_TARGET"

# --- 1. Stage source files (composer-managed paths excluded; composer install repopulates them).
mkdir -p "$NOVAAK_BUILD_DIR"
rsync -a --delete \
  --exclude='/.git' \
  --exclude='/.ddev' \
  --exclude='/.claude' \
  --exclude='/.idea' \
  --exclude='/.vscode' \
  --exclude='/.browser-sessions' \
  --exclude='/vendor' \
  --exclude='/web/core' \
  --exclude='/web/libraries' \
  --exclude='/web/modules/contrib' \
  --exclude='/web/profiles/contrib' \
  --exclude='/web/themes/contrib' \
  --exclude='/drush/Commands/contrib' \
  --exclude='/web/sites/default/files' \
  --exclude='/web/sites/default/settings.local.php' \
  --exclude='/web/sites/default/services.yml' \
  --exclude='/web/sites/simpletest' \
  --exclude='node_modules' \
  --exclude='*.swp' \
  "$PROJECT_ROOT/" "$NOVAAK_BUILD_DIR/"

# --- 2. composer install in the build dir.
# --ignore-platform-reqs lets us install Drupal 11.x (declared php >=8.3) on a
# platform pinned to 8.2 (config.platform.php in composer.json). Combined with
# the patches in patches/php-8.2-compat/, this yields a vendor tree that boots
# on PHP 8.2 (home.pl serves 8.2.24 under their "PHP 8.3" panel option).
( cd "$NOVAAK_BUILD_DIR" && composer install --no-dev --no-progress --ignore-platform-reqs )

# --- 3. Copy the public files dir + DB dump from local DDEV.
rsync -a "$PROJECT_ROOT/web/sites/default/files/" "$NOVAAK_BUILD_DIR/web/sites/default/files/"

if [ "$NOVAAK_SKIP_DB" != "1" ]; then
  ( cd "$PROJECT_ROOT" && ddev export-db --file="$DB_DUMP" )
fi

# --- 4. Write production settings.php (no committed creds; built from env).
cat > "$NOVAAK_BUILD_DIR/web/sites/default/settings.php" <<'PHPEOF'
<?php
// phpcs:ignoreFile

// Production settings for novaak.net/konduktiv_ovodaert/web (home.pl, PHP 8.2).
// Generated by scripts/deploy-novaak.sh — do not edit by hand on the server.

$databases = [];
$settings = [];
$config = [];

$databases['default']['default'] = [
  'database' => '__NOVAAK_DB_NAME__',
  'username' => '__NOVAAK_DB_USER__',
  'password' => '__NOVAAK_DB_PASS__',
  'prefix' => '',
  'host' => '__NOVAAK_DB_HOST__',
  'port' => '3306',
  'isolation_level' => 'READ COMMITTED',
  'driver' => 'mysql',
  'namespace' => 'Drupal\\mysql\\Driver\\Database\\mysql',
  'autoload' => 'core/modules/mysql/src/Driver/Database/mysql/',
];

$settings['hash_salt'] = '__NOVAAK_HASH_SALT__';
$settings['update_free_access'] = FALSE;
$settings['container_yamls'][] = $app_root . '/' . $site_path . '/services.yml';
$settings['file_scan_ignore_directories'] = ['node_modules', 'bower_components'];
$settings['entity_update_batch_size'] = 50;
$settings['entity_update_backup'] = TRUE;
$settings['state_cache'] = TRUE;
$settings['migrate_node_migrate_type_classic'] = FALSE;

$settings['trusted_host_patterns'] = [
  '^novaak\.net$',
  '^www\.novaak\.net$',
];

$settings['config_sync_directory'] = '../config/sync';

$config['system.performance']['css']['preprocess'] = TRUE;
$config['system.performance']['js']['preprocess'] = TRUE;
PHPEOF

# Substitute the env values into the placeholders.
sed -i \
  -e "s|__NOVAAK_DB_NAME__|${NOVAAK_DB_NAME}|" \
  -e "s|__NOVAAK_DB_USER__|${NOVAAK_DB_USER}|" \
  -e "s|__NOVAAK_DB_PASS__|${NOVAAK_DB_PASS}|" \
  -e "s|__NOVAAK_DB_HOST__|${NOVAAK_DB_HOST}|" \
  -e "s|__NOVAAK_HASH_SALT__|${NOVAAK_HASH_SALT}|" \
  "$NOVAAK_BUILD_DIR/web/sites/default/settings.php"

# --- 5. Push the artifact.
rsync -avz --partial \
  --exclude='/.git' --exclude='/.ddev' --exclude='/.claude' \
  --exclude='/web/core/tests' \
  --exclude='/web/core/modules/*/tests' \
  --exclude='/web/modules/contrib/*/tests' \
  "$NOVAAK_BUILD_DIR/" "$NOVAAK_SSH:$NOVAAK_TARGET/"

# --- 6. Import DB + clear caches on the server.
if [ "$NOVAAK_SKIP_DB" != "1" ]; then
  echo "==> Uploading DB dump"
  scp "$DB_DUMP" "$NOVAAK_SSH:$NOVAAK_TARGET/.db-import.sql.gz"
  echo "==> Importing DB"
  ssh "$NOVAAK_SSH" "zcat $NOVAAK_TARGET/.db-import.sql.gz | mysql -u $NOVAAK_DB_USER -p'$NOVAAK_DB_PASS' -h $NOVAAK_DB_HOST $NOVAAK_DB_NAME && rm -f $NOVAAK_TARGET/.db-import.sql.gz"
  rm -f "$DB_DUMP"
fi

echo "==> Clearing Drupal caches on server"
ssh "$NOVAAK_SSH" "rm -rf $NOVAAK_TARGET/web/sites/default/files/php/twig/* && \
mysql -u $NOVAAK_DB_USER -p'$NOVAAK_DB_PASS' -h $NOVAAK_DB_HOST $NOVAAK_DB_NAME -e '
TRUNCATE cache_bootstrap; TRUNCATE cache_config; TRUNCATE cache_container;
TRUNCATE cache_data; TRUNCATE cache_default; TRUNCATE cache_discovery;
TRUNCATE cache_dynamic_page_cache; TRUNCATE cache_entity; TRUNCATE cache_menu;
TRUNCATE cache_page; TRUNCATE cache_render; TRUNCATE cachetags;'"

echo "==> Done. Verify: https://novaak.net/konduktiv_ovodaert/web/"
